---
"$schema": http://json-schema.org/draft-07/schema#
"$id": https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/JobCheckConnectionConfig.yaml
title: JobCheckConnectionConfig
description: job check connection config
type: object
additionalProperties: false
required:
  - connectionConfiguration
  - dockerImage
properties:
  connectionConfiguration:
    description: Integration specific blob. Must be a valid JSON string.
    type: object
    existingJavaType: com.fasterxml.jackson.databind.JsonNode
  uuid:
    description: Id of the connector resource. Used by the worker to retrieve connection configuration.
    type: object
    existingJavaType: java.util.UUID
  connectorType:
    description: Connector type. Used by the worker to retrieve connection configuration.
    type: string
# This just follows the field in StandardCheckConnectionInput.yaml.
  dockerImage:
    type: string
