apiVersion: v1
kind: Pod
metadata:
  name: kube-destination-sample
spec:
  restartPolicy: Never
  initContainers:
    - name: init
      image: busybox:1.28
      command: ["sh", "-c", "mkfifo /pipes/stdin && mkfifo /pipes/stdout"]
      volumeMounts:
        - name: airbyte-pipes
          mountPath: /pipes
  containers:
    - name: destination
      image: airbyte/destination-listen-and-echo:dev
      imagePullPolicy: Always
      command: ["sh", "-c", "cat /pipes/stdin | ./listen-and-echo.sh > /pipes/stdout"]
      volumeMounts:
        - name: airbyte-pipes
          mountPath: /pipes
    - name: socat-port-to-destination-in
      image: alpine/socat:1.7.4.1-r1
      command: ["sh", "-c", "socat -d -d -d - TCP-L:9001 > /pipes/stdin"]
      ports:
        - containerPort: 9001
      volumeMounts:
        - name: airbyte-pipes
          mountPath: /pipes
    - name: destination-out-to-socat-port
      image: alpine/socat:1.7.4.1-r1
      command: [
          "sh",
          "-c",
          "cat /pipes/stdout | socat -d -d -d - TCP:10.104.0.57:9001",
      ]
      volumeMounts:
        - name: airbyte-pipes
          mountPath: /pipes
  volumes:
    - name: airbyte-pipes
      emptyDir: {}
