# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

orbs:
  node: circleci/node@4.1.0
  
jobs:
  build:
    machine: # run the steps with Docker
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    resource_class: xlarge
    
    steps:
      - checkout
      - run: find . | grep -e '**gradle$' | md5sum > /tmp/gradle.hashes
      - restore_cache:
          key: gradle-{{ checksum "/tmp/gradle.hashes" }}
          name: Cache Gradle deps      

      - run: find . | grep -e '**package-lock.json$' | md5sum > /tmp/npm.hashes
      - restore_cache:
          key: npm-{{ checksum "/tmp/npm.hashes" }}
          name: Cache Node deps

      - run: node/install
        node-version: "14.7.0"

      - run:
          name: "Set Python Version"
          command: |
            pyenv install 3.7.9
            pyenv global 3.7.9
      - run:
          name: Install OpenJDK 14
          command: |
            sudo apt-get update && sudo apt-get install openjdk-14-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-14-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-14-openjdk-amd64/bin/javac
            java -version

