# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
    
jobs:
  build:
    machine: # run the steps with Docker
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    resource_class: xlarge
    
    steps:
      - checkout
      - run: find . | grep -e '**gradle$' | md5sum > build/gradle.hashes
      - restore_cache:
        path: ~/.gradle
        key: gradle-{{ checksum "build/gradle.hashes" }}
        name: Cache Gradle deps      

      - run: find . | grep -e '**package-lock.json$' | md5sum > build/npm.hashes
      - restore_cache:
        path: ~/.npm
        key: npm-{{ checksum "build/npm.hashes" }}
        name: Cache Node deps
        
      
      
      
