apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-server
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: airbyte
                    operator: In
                    values:
                      - scheduler
              topologyKey: kubernetes.io/hostname
