name: Fast CI

on:
  push:

jobs:
  build:
    env:
      GRADLE_PATH: /tmp/gradle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v2

      - name: Cache java deps
        uses: actions/cache@v2
        with:
          path: ${{ env.GRADLE_PATH }}
          key: gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            gradle-

      - name: Cache node deps
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-

      - name: build
        run: ./gradlew build
