name: Airbyte CI

on:
  schedule:
    - cron: '0 */6 * * *'
  push:

jobs:
  build:
    env:
      GRADLE_PATH: /tmp/gradle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Airbyte
        uses: actions/checkout@v2

