name: publish-cdk
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'dry-run'
        required: false
      comment-id:
        description: 'The comment-id of the slash command. Used to update the comment with the status.'
        required: false

jobs:
  publish-cdk:
    name: Do the job on the runner
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo 'Hello World!'
      - name: Link comment to workflow run
        if: github.event.inputs.comment-id
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.inputs.comment-id }}
          body: |
            > :clock2: ${{github.event.inputs.connector}} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
