name: publish-cdk
on:
  workflow_dispatch:
    inputs:
      comment-id:
        description: 'The comment-id of the slash command. Used to update the comment with the status.'
        required: false

jobs:
  publish-cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo 'Hello World!'
      - name: Add Success Comment
        if: github.event.inputs.comment-id && success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.inputs.comment-id }}
          body: |
            > :white_check_mark: ${{github.event.inputs.connector}} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
      - name: Add Failure Comment
        if: github.event.inputs.comment-id && !success()
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.inputs.comment-id }}
          body: |
            > :x: ${{github.event.inputs.connector}} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
