# See [Source Acceptance Tests](https://docs.airbyte.io/connector-development/testing-connectors/source-acceptance-tests-reference)
# for more information about how to configure these tests
connector_image: airbyte/source-monday:dev
tests:
  spec:
    - spec_path: "source_monday/spec.json"
  connection:
    - config_path: "secrets/config.json"
      status: "succeed"
    - config_path: "secrets/config_oauth.json"
      status: "succeed"
    - config_path: "secrets/config_api_token.json"
      status: "succeed"
    - config_path: "integration_tests/invalid_config.json"
      status: "failed"
    - config_path: "integration_tests/invalid_oauth_config.json"
      status: "failed"
    - config_path: "integration_tests/invalid_api_token_config.json"
      status: "failed"
  discovery:
    - config_path: "secrets/config.json"
  basic_read:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
  full_refresh:
    - config_path: "secrets/config.json"
      configured_catalog_path: "integration_tests/configured_catalog.json"
